CE080_Vedant_Parikh

Machine Learning

Lab : 04

### ***Linear regression using PyTorch built-ins*** 

#### ***Define DataLoader***

In [1]:
import numpy as np
import torch

In [5]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [6]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [7]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [8]:
from torch.utils.data import TensorDataset

In [9]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [10]:
from torch.utils.data import DataLoader

In [11]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [12]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 22.,  37.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.]])


#### ***nn.Linear***

In [13]:
import torch.nn as nn

In [14]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4998,  0.0560, -0.4500],
        [ 0.3809, -0.5480, -0.3097]], requires_grad=True)
Parameter containing:
tensor([0.5260, 0.0421], requires_grad=True)


In [15]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4998,  0.0560, -0.4500],
         [ 0.3809, -0.5480, -0.3097]], requires_grad=True),
 Parameter containing:
 tensor([0.5260, 0.0421], requires_grad=True)]

In [16]:
preds = model(inputs)
preds

tensor([[ 21.4144, -22.1892],
        [ 22.1371, -33.3458],
        [ 25.4140, -58.2188],
        [ 37.2649,   3.8659],
        [  8.8892, -47.9669]], grad_fn=<AddmmBackward0>)

#### ***loss functions***

In [17]:
import torch.nn.functional as F

In [18]:
loss_fn = F.mse_loss

In [19]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(11459.7314, grad_fn=<MseLossBackward0>)


#### ***Optimizer***

In [20]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

#### ***Train for multiple epochs***

In [22]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [23]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 1451.0312
Epoch [20/100], Loss: 1033.8561
Epoch [30/100], Loss: 912.4698
Epoch [40/100], Loss: 810.1976
Epoch [50/100], Loss: 720.0988
Epoch [60/100], Loss: 640.6330
Epoch [70/100], Loss: 570.5319
Epoch [80/100], Loss: 508.6801
Epoch [90/100], Loss: 454.0953
Epoch [100/100], Loss: 405.9123


In [24]:
prediction = model(inputs)
prediction

tensor([[ 63.3170,  77.0917],
        [ 80.4385, 100.6356],
        [112.8265, 122.1331],
        [ 55.7284,  75.9270],
        [ 78.7292,  96.3794]], grad_fn=<AddmmBackward0>)

In [25]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [26]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[60.9179, 76.0550]], grad_fn=<AddmmBackward0>)