CE080_Vedant_Parikh

Machine Learning

Lab : 01

Q-1 : Create a Numpy array of size 4 x 5.

In [1]:
import numpy as np
array1 = [1, 2, 3, 4, 5]
array2 = [2, 3, 4, 5, 6]
array3 = [3, 4, 5, 6, 7]
array4 = [4, 5, 6, 7, 8]
npmatrix1 = np.array([array1, array2, array3, array4])
print(npmatrix1)
print(type(npmatrix1))

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
<class 'numpy.ndarray'>


Q-2 : Randomly initialize the array.


In [2]:
arr1 = np.random.rand(4, 4)
print(arr1)

[[0.64129341 0.34435609 0.1619535  0.05745618]
 [0.11943106 0.18369645 0.92045551 0.29038469]
 [0.9865139  0.79830532 0.75300034 0.77894878]
 [0.24098662 0.30379336 0.94619145 0.97881351]]


Q-3 : Get the Determinant and Transpose of the Matrix that you created.

In [3]:
arr1 = np.random.rand(4, 4)
det = np.linalg.det(arr1)
print("Determinant is:-", int(det))
print("Transpose is:-", arr1.T)

Determinant is:- 0
Transpose is:- [[0.19274837 0.98212988 0.42897894 0.39871709]
 [0.83493243 0.40971543 0.33377272 0.53736609]
 [0.74338033 0.35500556 0.50344993 0.5136021 ]
 [0.47899937 0.70575014 0.79589223 0.93238875]]


Q-4 : Create another matrix of size 5 x 4 and randomly initialize it.

In [4]:
arr1 = np.random.rand(5, 4)
print(arr1)

[[0.84006627 0.45947789 0.7157863  0.65615907]
 [0.96886916 0.26403874 0.62778854 0.33828594]
 [0.34544178 0.18452744 0.04928784 0.97291112]
 [0.24746884 0.01394824 0.8341674  0.39943435]
 [0.04167014 0.93058488 0.0579714  0.62337758]]


Q-5 : Perform Matrix multiplication.

In [5]:
array1 = [[1, 2], [1, 2]]
array2 = [[2, 3], [2, 3]]
np.matmul(array1, array2)

array([[6, 9],
       [6, 9]])

Q-6 : Perform element wise matrix multiplication.

In [6]:
array1 = [1, 2, 3, 4, 5]
array2 = [2, 3, 4, 5, 6]
np.multiply(array1, array2)

array([ 2,  6, 12, 20, 30])

Q-7 : Find mean, median of the numpy array created.

In [7]:
print("Mean of whole matrix:-")
print(np.mean(npmatrix1))
print("Mean by column:-",np.mean(npmatrix1, axis = 0))
print("Mean by column:-",np.mean(npmatrix1, axis = 0))
print("Median is:-",np.median(npmatrix1))

Mean of whole matrix:-
4.5
Mean by column:- [2.5 3.5 4.5 5.5 6.5]
Mean by column:- [2.5 3.5 4.5 5.5 6.5]
Median is:- 4.5


Q-8 : Obtain each row in the second column of the first array.

In [8]:
print(npmatrix1[:,2])

[3 4 5 6]


Q-9 : Study about numpy array attributes and implement it on the first matrix.

In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = arr.shape
arr2 = arr.reshape(3, 2)
print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 (2, 3)
arr2:
 [[1 2]
 [3 4]
 [5 6]]
