CE080_Vedant_Parikh

Machine Learning

Lab : 04

### ***Linear regression model from scratch*** 

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [6]:
inputs @ weight.t() + bias

tensor([[-198.6156,  -26.7580],
        [-271.4157,  -20.7641],
        [-276.0429,  -30.9838],
        [-206.0426,  -60.4041],
        [-264.0466,    8.0755]], grad_fn=<AddBackward0>)

In [7]:
def model(inputs):
    return inputs @ weight.t() + bias

In [8]:
prediction = model(inputs)
print(prediction)

tensor([[-198.6156,  -26.7580],
        [-271.4157,  -20.7641],
        [-276.0429,  -30.9838],
        [-206.0426,  -60.4041],
        [-264.0466,    8.0755]], grad_fn=<AddBackward0>)


### ***Loss function*** 

In [9]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(58731.2578, grad_fn=<DivBackward0>)

In [10]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [11]:
loss = mse(prediction, targets)
print(loss)

tensor(58731.2578, grad_fn=<DivBackward0>)


### ***Compute gradients*** 

In [12]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-26722.4141, -29209.9785, -18109.2812],
        [ -8661.0938,  -9450.7969,  -5692.8452]])
tensor([-319.4327, -102.3669])


### ***Train the model using gradient descent*** 

In [13]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [14]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(39683.4453, grad_fn=<DivBackward0>)


In [15]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [16]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(212.0650, grad_fn=<DivBackward0>)


In [17]:
prediction

tensor([[ 60.9882,  57.1441],
        [ 72.2041,  89.0405],
        [135.2977, 103.1879],
        [ 41.6574,  20.8080],
        [ 72.5878, 114.1388]], grad_fn=<AddBackward0>)

In [18]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])